# This is a basic workflow to help you get started with Actions

name: baby-monitor-docker-push

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2
        
      - name: Set up QEMU 🏗️
        uses: docker/setup-qemu-action@v1
        
      - name: Set up Docker Buildx 🐋
        uses: docker/setup-buildx-action@v1
      
      - name: Delete Latest JFrog Docker Repo
        run: |
          curl -v -u ${{ secrets.JFROG_USER_WRITER }}:${{ secrets.JFROG_PASSWORD_WRITER }} \
               -X DELETE "https://savimonty.jfrog.io/artifactory/savimonty-docker-local/baby-monitor-server"
          
      - name: Login to JFrog 🐸  
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.JFROG_OWNER }}.jfrog.io
          username: ${{ secrets.JFROG_USER_WRITER }}
          password: ${{ secrets.JFROG_PASSWORD_WRITER }}
          
      - name: Build and push 🐳
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          platforms: linux/aarch64
          tags: ${{ secrets.JFROG_OWNER }}.jfrog.io/savimonty-docker/baby-monitor-server:latest
